# This file is needed by AWS CodeDeploy to know how to properly deploy the application from GitHub to an EC2 instance
# Template modified from https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorials-github-upload-sample-revision.html
version: 0.0
os: linux
files:
  - source: /.
    destination: /home/ec2-user/Running-App
hooks:
  AfterInstall:
    - location: codedeploy_scripts/start.sh
      timeout: 300
      runas: root
#   ApplicationStop:
#     - location: codedeploy_scripts/stop_server
#       timeout: 300
#       runas: root