# This file is needed by AWS CodeDeploy to know how to properly deploy the application from GitHub to an EC2 instance
# Template modified from https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorials-github-upload-sample-revision.html
version: 0.0
os: linux
files:
  - source: /.
    destination: /home/ec2-user/Running-App
hooks:
  BeforeInstall:
    - location: codedeploy_scripts/stop_service.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy_scripts/npm_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy_scripts/setup_systemd_env.sh
      timeout: 300
      runas: root
    - location: codedeploy_scripts/start_service.sh
      timeout: 300
      runas: root