# This file is needed by AWS CodeDeploy to know how to properly deploy the application
version: 0.0
os: linux
files:
  - source: /.
    destination: /home/ec2-user/Running-App
# hooks:
#   BeforeInstall:
#     - location: scripts/install_dependencies
#       timeout: 300
#       runas: root
#     - location: scripts/start_server
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: scripts/stop_server
#       timeout: 300
#       runas: root