create table if not exists
  public.users (
    username character varying not null,
    password character varying not null,
    email character varying not null,
    verified character varying not null default 'N'::character varying,
    created_at timestamp with time zone not null default now(),
    id bigint generated by default as identity,
    constraint users_pkey primary key (id),
    constraint users_email_key unique (email)
  ) tablespace pg_default;
  
create table if not exists
  public.progress (
    id bigint not null,
    _5k text not null default '0000000000000000000000000000000000000000000000000000000000000000'::text,
    created_at timestamp with time zone not null default now(),
    _10k text not null default '0000000000000000000000000000000000000000000000000000000000000000'::text,
    constraint progress_pkey primary key (id),
    constraint progress_id_fkey foreign key (id) references users (id)
  ) tablespace pg_default;
  
create table if not exists
  public.password_reset_tokens (
    user_id bigint not null,
    token character varying not null,
    token_expiration timestamp without time zone not null,
    created_at timestamp with time zone not null default now(),
    constraint password_reset_tokens_pkey primary key (user_id, token),
    constraint password_reset_tokens_token_key unique (token),
    constraint public_password_reset_tokens_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;